In [1]:
import numpy as np

In [2]:
test_example = np.array([[1,2,3],[4.5,5,6]],int)
test_example

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
test_example[0][2]

3

In [4]:
test_example[0,2]

3

In [7]:
test_example[0,2] = 5
test_example

array([[1, 2, 5],
       [4, 5, 6]])

In [9]:
test_example = np.array([
    [1,2,5,8],[1,2,5,8],[1,2,5,8],[1,2,5,8]],int
)
test_example

array([[1, 2, 5, 8],
       [1, 2, 5, 8],
       [1, 2, 5, 8],
       [1, 2, 5, 8]])

In [12]:
test_example[:3,1:3]

array([[2, 5],
       [2, 5],
       [2, 5]])

In [13]:
test_example[1,:2]

array([1, 2])