In [2]:
import numpy as np

In [3]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
a<5

array([ True,  True,  True,  True,  True, False, False, False, False, False], dtype=bool)

In [7]:
np.any(a>5), np.any(a<0)

(True, False)

In [9]:
np.all(a>5), np.all(a<5)

(False, False)

In [12]:
np.all(a>5), np.all(a<10)

(False, True)

In [17]:
a = np.array([1,3,0],float)
a

array([ 1.,  3.,  0.])

In [19]:
a>0

array([ True,  True, False], dtype=bool)

In [21]:
np.where(a>0,3,2)

array([3, 3, 2])

In [26]:
a = np.arange(5,15)
a

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [27]:
a>10

array([False, False, False, False, False, False,  True,  True,  True,  True], dtype=bool)

In [28]:
np.where(a>10) #참인 인덱스 리스트 반환.

(array([6, 7, 8, 9]),)

In [30]:
np.isnan(a)

array([False, False, False, False, False, False, False, False, False, False], dtype=bool)

In [32]:
np.isfinite(a)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,  True], dtype=bool)

In [34]:
a = np.array([1,2,4,5,8,78,23,3])
a

array([ 1,  2,  4,  5,  8, 78, 23,  3])

In [38]:
np.argmax(a), np.argmin(a) #인덱스 출력임.

(5, 0)

In [40]:
a = np.array([[1,2,4,7],[9,88,6,45],[9,76,3,4]])
np.argmax(a, axis=1), np.argmin(a, axis=0)

(array([3, 1, 1]), array([0, 0, 2, 2]))