In [1]:
import numpy as np

In [2]:
test_array = np.array([1,4,0,2,3,8,9,7],float)
test_array>3

array([False,  True, False, False, False,  True,  True,  True], dtype=bool)

In [3]:
test_array[test_array>3]

array([ 4.,  8.,  9.,  7.])

In [4]:
condition = test_array < 3
condition

array([ True, False,  True,  True, False, False, False, False], dtype=bool)

In [5]:
test_array[condition]

array([ 1.,  0.,  2.])

In [6]:
a = np.array([2,4,6,8],float)
b = np.array([0,0,1,3,2,1],int)
a[b]

array([ 2.,  2.,  4.,  8.,  6.,  4.])

In [7]:
a.take(b)

array([ 2.,  2.,  4.,  8.,  6.,  4.])

In [8]:
a = np.array([[1,4],[9,16]],float)
b = np.array([0,0,1,1,0],int)
c = np.array([0,1,1,1,1],int)
a[b,c]

array([  1.,   4.,  16.,  16.,   4.])

In [9]:
a[b]

array([[  1.,   4.],
       [  1.,   4.],
       [  9.,  16.],
       [  9.,  16.],
       [  1.,   4.]])